### ISSUE TITLE
gulp issue on Windows (10)

### ISSUE THREAD

**Issue by dpastoor** [airtoxin/Electron-React-Boilerplate#3]
Also figured I'd try it out on windows - getting a similar bug, here is the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart atomshell-react-boilerplate@0.0.1
7 info start atomshell-react-boilerplate@0.0.1
8 verbose unsafe-perm in lifecycle true
9 info atomshell-react-boilerplate@0.0.1 Failed to exec start script
10 verbose stack Error: atomshell-react-boilerplate@0.0.1 start: `gulp`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid atomshell-react-boilerplate@0.0.1
12 verbose cwd C:\Users\devin\Documents\Repos\Electron-React-Boilerplate
13 error Windows_NT 6.3.9600
14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error atomshell-react-boilerplate@0.0.1 start: `gulp`
18 error Exit status 1
19 error Failed at the atomshell-react-boilerplate@0.0.1 start script 'gulp'.
19 error This is most likely a problem with the atomshell-react-boilerplate package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     gulp
19 error You can get their info via:
19 error     npm owner ls atomshell-react-boilerplate
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

I will try with your update on OSX from #2 shortly

**Comment by airtoxin** [comment]
It looks gulp command not found error.
`npm install -g gulp` needed?

**Comment by airtoxin** [comment]
Or more problem about path string difference between OS.
Those path string `/` and glob `**/*` won't work on windows?
![screenshot 2015-05-14 10 32 28](https://cloud.githubusercontent.com/assets/2460874/7624522/c64c63fc-fa24-11e4-83a1-0775c0ccbc24.png)

**Comment by dpastoor** [comment]
regarding #2 the `npm install -g gulp` plus maybe? your update and a new `npm i` has gotten through the gulp pre-processing. It is currently pulling down the new version of electron but so far looking good. You might be right regarding the `/` strings for windows - I will give a shot changing those and see if that allows it to build

**Comment by dpastoor** [comment]
so maybe silly question, but everything seems to build fine, does this boilerplate actually contain a simple window or anything that is supposed to pop up? 

I just get this

![image](https://cloud.githubusercontent.com/assets/3196313/7625122/958f0264-f9c1-11e4-8506-3e1d42af12c7.png)

**Comment by airtoxin** [comment]
It's a very simple application on build directory.
![screenshot 2015-05-14 23 31 43](https://cloud.githubusercontent.com/assets/2460874/7633780/6ba148ec-fa91-11e4-9547-28ce50586393.png)

It seems that your build is succeed.
Please PR your changes?

**Comment by dpastoor** [comment]
ah got it - I didn't realize you had to open it in the build directory - didn't actually change anything so no PR needed, it was the npm install -g gulp that fixed it!

**Comment by dpastoor** [comment]
ah just realized you meant the PR for windows - yes it doesn't work there yet. I will try to give it a shot and see what I can do.

**Comment by airtoxin** [comment]
:+1:
