### ISSUE TITLE
Dev tools doesn't appear.

### ISSUE THREAD

**Issue by freele** [airtoxin/Electron-React-Boilerplate#4]
I found sample app code quite handy for development, at least at first steps - [Sample app](https://github.com/atom/electron/blob/f5fbd52dbdd0a27e7a19725be86b94cc35119739/atom/browser/default_app/default_app.js#L121). 
I could make PR with something like that if you approve that it fits your boilerplate idea.

**Comment by airtoxin** [comment]
@freele It's good idea. PRs welcome.
